# Generated by Django 6.0.3 on 2026-09-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('draft_text', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('context', models.TextField(blank=True)),
                ('need', models.TextField(blank=True)),
                ('users', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('expected_result', models.TextField(blank=True)),
                ('success_criteria', models.TextField(blank=True)),
                ('business_contact', models.CharField(blank=True, max_length=200)),
                ('interaction_format', models.CharField(blank=True, max_length=200)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('readiness_level', models.CharField(default='draft', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('closed', 'Закрыта')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-score', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('interests', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('technologies', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('plan', models.TextField()),
                ('timeline', models.CharField(max_length=200)),
                ('prototype_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='challenges.businesstask')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='challenges.teamprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
